import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Roboto } from 'next/font/google'

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const roboto = Roboto({
	weight: ['400', '500', '800'],
	style: ['normal', 'italic'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
})

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} font-sans`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
